version: '3'

services:
  db:
    image: mysql:8.0
    container_name: expense-tracker-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - expense-tracker-db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: expense-tracker-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./expense-tracker
      dockerfile: Dockerfile.frontend
    container_name: expense-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  expense-tracker-db-data: